### PR TITLE
Fix. This fixes #151 Error on invoke init functions when state is null

### LINKED ISSUE #151: [BUG] Error on invoke init functions when state is null
**Describe the bug**
Error on invoke init functions when state is null.

**To Reproduce**
Define an actor with an init function and ensure that no rows from this actor appear in the statestore. When starting the system will show an error on the call to the init function.

Ator:
```elixir
defmodule SpawnSdkExample.Actors.JoeActor do
  use SpawnSdk.Actor,
    name: "joe",
    state_type: Io.Eigr.Spawn.Example.MyState,
    deactivate_timeout: 60_000,
    snapshot_timeout: 2_000

  require Logger
  alias Io.Eigr.Spawn.Example.{MyState, MyBusinessMessage}

  defact init(%Context{state: state} = ctx) do
    Logger.info("[joe] Received InitRequest. Context: #{inspect(ctx)}")

    %Value{}
    |> Value.state(state)
    |> Value.reply!()
  end

  defact sum(%MyBusinessMessage{value: value} = data, %Context{state: state} = ctx) do
    Logger.info("[joe] Received Request: #{inspect(data)}. Context: #{inspect(ctx)}")

    new_value =
      if is_nil(state) do
        0 + value
      else
        (state.value || 0) + value
      end

    response = %MyBusinessMessage{value: new_value}

    %Value{}
    |> Value.of(response, %MyState{value: new_value})
    |> Value.broadcast(Broadcast.to("external.channel", response))
    |> Value.reply!()
  end
end

```

**Expected behavior**
System cannot boot with errors.

**Spawn Proxy (please complete the following information):**
 - Version >= 0.5.0

### PR DESCRIPTION
**Pull request by sleipnir**

### CODE REVIEW

File: spawn_sdk/spawn_sdk/lib/system/spawn_system.ex [hunk 1]
```diff
@@ -175,6 +175,11 @@ defmodule SpawnSdk.System.SpawnSystem do
     actors
   end
 
+  def delete_cached_actors(system, actors) do
+    :ets.delete(:"#{system}:actors", {"actors", state_to_map(actors)})
```
Comment (eliasdarruda) [inline spawn_sdk/spawn_sdk/lib/system/spawn_system.ex:179]:
```suggestion
    :ets.delete(:"#{system}:actors", {"actors", actors})
```

**Review by eliasdarruda — APPROVED** [review]
